### ISSUE TITLE
Using PC through JSPM

### ISSUE THREAD

**Issue by AutoSponge** [crcn/paperclip.js#264]
I've noticed a few things with v2.0.3 that may be of interest to others:
1. You can't use the npm version, see ~2.
2. When you install `jspm install --save paperclip=github:mojo-js/paperclip.js` you still have to update the entry in your `config.js` file to `"paperclip": "github:mojo-js/paperclip.js@2.0.3/dist/paperclip.min"`. For some reason, the other file can't find most of its references.
3. (possibly related to symptoms of ~1) When you use pc in your app, you'll need to do something like this:

``` js
import window from 'global/window';
import 'paperclip';
const paperclip = window.paperclip;
```

It seems that pc doesn't export anything that jspm can detect (even the global), so you have to pull it off the window object.

I'll try to take a look this weekend at how pc is exporting/registering.

**Comment by crcn** [comment]
I'll take a look at the JSPM docs here in a bit and figure out a good solution for paperclip. It seems like this command works properly: `jspm install npm:paperclip`.

My only concern with installing paperclip via the GitHub  is versioning. You might get an incompatible build. I *do* add [semver](http://semver.org/) [tags](https://github.com/mojo-js/paperclip.js/releases) for various releases. Dunno however if `jspm` supports that.

**Comment by AutoSponge** [comment]
@crcn The command works, but the `paperclip` object is not exposed by the entry (node) module. If it would help, I can set up a repo with the example.

**Comment by AutoSponge** [comment]
@crcn I just did a clean [experiment](https://github.com/AutoSponge/jspm-paperclip) in which I only had to change the entry point to `/lib` to get it working. That may be solved with a simple change in the `package.json`. I think for browserify you can set the `browser` property (see https://gist.github.com/defunctzombie/4339901) and make `main` point to `/lib`.

**Comment by crcn** [comment]
Odd that JSPM is installing `3.0.3` instead of `2.0.5` by default. `jspm install npm:paperclip@2.0.5` should work.

In the meantime, I'll take a look into the exception you're seeing with the `3.x` branch.

**Comment by crcn** [comment]
Guessing this works. I'll verify here in a bit to make sure paperclip is working properly in jspm.
