### ISSUE TITLE
Using Gulp to Parse Templates

### ISSUE THREAD

**Issue by AutoSponge** [crcn/paperclip.js#287]
``` javascript
import fs from 'fs';
import gulp from 'gulp';
import {parse} from 'paperclip/lib/parser';
const {$} = gulp;

export default () => gulp.src('app/scripts/**/*.html')
  .pipe($.tap(file => fs.writeFileSync(file.path + '.js', parse(file.contents.toString()))));
```

I'm interested if anyone has a better/different task setup. This seems to work for now.

**Comment by crcn** [comment]
If you're using [jspm](http://jspm.io/), you should be able to register a custom plugin that enables you to import/require paperclip templates into your javascript files. Kinda like this:

```javascript
var pc = require("paperclip");

// hello {{name}}!
var tpl = pc.template(require("./template.pc"));

var view = tpl.view({ name: "Zoolander" });

document.body.appendChild(view.render());
```

Found the docs on this for jspm here: https://github.com/jspm/jspm-cli/wiki/Plugins.

**Comment by AutoSponge** [comment]
I was including the html versions directly using the text plugin which worked fine. For the production workflow, I wanted to pre-compile/pre-parse to js. But that's an alternative, thanks.

**Comment by crcn** [comment]
Would it be helpful to have a `gulp-paperclip` module for this sort of thing?

**Comment by AutoSponge** [comment]
I have faith that more people using pc will evolve a (preferred) workflow. I'm not convinced what I've done is awesome.
