### ISSUE TITLE
Content security issues (FF, Edge, IE)

### ISSUE THREAD

**Issue by benaadams** [crcn/paperclip.js#300]
When 'unsafe-eval' is disallowed by the [Content-Security-Policy](http://content-security-policy.com/) http header 

```javascript
new Function( string )
```
breaks the model binding in Firefox and Edge+IE even if the templates are precompiled due to [this line](https://github.com/mojo-js/paperclip.js/blob/11be00b982aed7e16951b64b63d45ce9e1e0e2fa/lib/view/index.js#L68):

```javascript
getter = this._getters[pt] = new Function("return this." + pt);
```

however the following should work:
```javascript
getter = this._getters[pt] = function(){ return this[pt]; };
```

Just checking the closure fixes it; and doesn't break the binding in a different way...

**Comment by benaadams** [comment]
Hmm... keypath could be x.y.z.w so would need loop for array :-/

**Comment by benaadams** [comment]
K, not sure of a good fix for this

**Comment by crcn** [comment]
Nice catch! Didn't realize this would cause issues in certain browsers. I'll put a little thought into a good fix, but the short answer would probably be to loop through an array of key paths. Should still be fast enough.
