### ISSUE TITLE
template() broken after 3.0.7

### ISSUE THREAD

**Issue by davidcalhoun** [crcn/paperclip.js#303]
Looks like template() isn't working as expected after 3.0.7.

To reproduce:

```javascript
paperclip.template('{{foo}}');
```

Result:

Uncaught TypeError: options.compile is not a function

The error points to this code:

    // TODO - use options parser here
    createVNode = typeof source === "string" ? options.compile(source, options) : source;

In 3.0.6 this works as expected:

```javascript
paperclip.template('{{foo}}');
// returns: Template {vnode: DynamicNode, _hydrators: Array[1], options: Object, modifiers: Object, section: NodeSection}
```

**Comment by crcn** [comment]
Odd  - I'll see what's going on.

**Comment by davidcalhoun** [comment]
Cool, thanks!
