### ISSUE TITLE
Add option to append DOM node

### ISSUE THREAD

**Issue by tomekmarchi** [crcn/paperclip.js#305]
When inserting items PC should check to see if the item is a DOM node if so append it to said spot.
`<div id="mainWrap">{{(navBar}}</div>`
In this case consider navBar to be a DOM node.

**Comment by crcn** [comment]
Definitely seems like a good thing to add. However right now `{{blocks}}` are transpiled into text nodes, so this feature will have to implemented as a component. For example:

```html
<div id="mainWrap"><node value={{navBar}} /></div>
```

Open to other ideas though.

**Comment by tomekmarchi** [comment]
Loving out of 10
`<{{navBar}} />`
